
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

python_script:

# services:
#   - service: python_script.turn_on_ceiling_lights
#     target:
#       entity_id: light.bedroom
#     data:
#       rgb_color: [255, 0, 0]