
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

services:
  - service: python_script.turn_on_light
    target:
      entity_id: light.bedroom
    data:
      rgb_color: [255, 0, 0]