
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

python_script:

logger:
  default: warning

  # log level for all python scripts
  homeassistant.components.python_script: info