turn_on_light:
  name: Turn on light
  description: Turn on a specific light and set its color according to time and weather.
  fields:
    entity_id:
      description: The light that will be turned on.
      example: light.bedroom